language: php

php:
  - 5.4
  - 5.3

env:
  - SYMFONY_VERSION="2.3.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar --dev --prefer-source install